# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-03 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AXF1806', '0008_maininfo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='maininfo',
            table='axf_mainshow',
        ),
    ]
