# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-20 06:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='名字')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teach.Item', verbose_name='商品')),
            ],
            options={
                'db_table': 'cart',
                'ordering': ['-id'],
            },
        ),
    ]
