# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-03 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0006_auto_20180703_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeid', models.CharField(max_length=40)),
                ('typename', models.CharField(max_length=10)),
                ('childtypenames', models.CharField(max_length=200)),
                ('typesort', models.IntegerField()),
            ],
            options={
                'db_table': 'axf_foodtypes',
            },
        ),
    ]
