# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-03 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0008_goods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='productlongname',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='goods',
            name='productname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
