# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-19 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='s_class',
            field=models.CharField(max_length=30),
        ),
    ]
