# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-20 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='班级名')),
                ('creat_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='学生名')),
                ('creat_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('score', models.FloatField(verbose_name='成绩')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Class', verbose_name='班级id')),
            ],
        ),
    ]
