# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-27 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('t7', '0003_auto_20180627_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stu',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='t7.Grade', verbose_name='所属班级'),
        ),
    ]
