# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-25 17:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AXF', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='homewheel',
            table='axf_wheel',
        ),
    ]
