# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-29 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AXF', '0010_cartmodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cartmodel',
            table='axf_cart',
        ),
    ]
