# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-30 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AXF', '0011_auto_20180529_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_goods_num', models.IntegerField(default=1)),
                ('o_goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AXF.Goods')),
            ],
            options={
                'db_table': 'axf_ordergoods',
            },
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_status', models.IntegerField(default=0)),
                ('o_time', models.DateTimeField(auto_now=True)),
                ('o_price', models.FloatField(default=0)),
                ('o_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AXF.UserModel')),
            ],
            options={
                'db_table': 'axf_order',
            },
        ),
        migrations.AddField(
            model_name='ordergoods',
            name='o_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AXF.OrderModel'),
        ),
    ]
