# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-27 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app07', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stu',
            name='age',
            field=models.IntegerField(default=18, verbose_name='年纪'),
        ),
    ]
