# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-27 03:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app07', '0002_auto_20180627_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='班级名字')),
                ('type', models.CharField(max_length=20, verbose_name='班级类型')),
            ],
        ),
        migrations.AddField(
            model_name='stu',
            name='grade',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='app07.Grade', verbose_name='所属班级'),
        ),
    ]
