# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-27 03:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app07', '0003_auto_20180627_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stu',
            name='grade',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app07.Grade', verbose_name='所属班级'),
        ),
    ]
