# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-21 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akaizi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stu',
            name='grade',
            field=models.IntegerField(null=True, verbose_name='成绩'),
        ),
    ]
