# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-23 09:09
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('akaizi', '0002_stu_grade'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='stu',
            managers=[
                ('my_manage', django.db.models.manager.Manager()),
            ],
        ),
    ]
