# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-20 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Myclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='班名')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('isactive', models.BooleanField(verbose_name='活跃度')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, verbose_name='姓名')),
                ('stime', models.DateTimeField(auto_now_add=True, verbose_name='进班时间')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('grade', models.FloatField(verbose_name='成绩')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Myclass', verbose_name='班级ID')),
            ],
        ),
    ]
