# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-20 03:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='分类名')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, verbose_name='商品')),
                ('barcode', models.CharField(max_length=15, null=True, verbose_name='条码')),
                ('price', models.FloatField(verbose_name='售价')),
                ('in_price', models.DecimalField(decimal_places=2, max_digits=13, verbose_name='进货价')),
                ('come_in_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('icon', models.CharField(max_length=30, null=True, verbose_name='封皮')),
                ('categary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ashuang.Categary', verbose_name='所属分类')),
            ],
        ),
    ]
