# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-21 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashuang', '0002_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='icon',
            field=models.CharField(max_length=300, null=True, verbose_name='封皮'),
        ),
    ]
