# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-21 06:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('t3', '0002_stu_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=20)),
                ('org', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='人名')),
                ('age', models.IntegerField(default=1, verbose_name='年纪')),
                ('id_card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='t3.IdCard', verbose_name='身份证')),
            ],
        ),
        migrations.AlterModelManagers(
            name='stu',
            managers=[
                ('my_manage', django.db.models.manager.Manager()),
            ],
        ),
    ]
