# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-21 07:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('t3', '0003_auto_20180621_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='id_card',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='t3.IdCard', verbose_name='身份证'),
        ),
    ]
