# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-21 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t3', '0005_auto_20180621_0753'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名字')),
                ('age', models.IntegerField(default=5, verbose_name='年龄')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='书名')),
                ('authors', models.ManyToManyField(to='t3.Author', verbose_name='作者')),
            ],
        ),
    ]
