# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-21 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t3', '0006_author_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名字')),
                ('sex', models.CharField(default='雌性', max_length=4)),
                ('eat', models.CharField(max_length=20, verbose_name='吃')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名字')),
                ('sex', models.CharField(default='雌性', max_length=4)),
                ('hobby', models.CharField(max_length=20, verbose_name='爱好')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
